// Level configuration for Gradient Puzzle game

export interface LevelConfig {
  id: string;
  name: string;
  description?: string;
  cols: number;
  rows: number;
  // 4-corner gradient colors for bilinear interpolation
  colors: {
    topLeft: string;
    topRight: string;
    bottomLeft: string;
    bottomRight: string;
  };
  anchors: number[];
  tileShape: 'square' | 'hexagon' | 'circle';
  gap?: number;
}

export interface LevelPack {
  id: string;
  name: string;
  description: string;
  levels: LevelConfig[];
}

// Level packs with 4-corner gradients
export const LEVEL_PACKS: LevelPack[] = [
  {
    id: 'tutorial',
    name: 'Обучение',
    description: 'Простые уровни для знакомства с игрой',
    levels: [
      {
        id: 'tutorial-1',
        name: 'Первые шаги',
        cols: 3,
        rows: 3,
        colors: {
          topLeft: '#cc952e',
          topRight: '#db4734',
          bottomLeft: '#f1660f',
          bottomRight: '#e74c3c',
        },
        anchors: [0, 2, 4, 6, 8],
        tileShape: 'square',
      },
      {
        id: 'tutorial-2',
        name: 'Рассвет',
        cols: 4,
        rows: 3,
        colors: {
          topLeft: '#1a1a2e',
          topRight: '#4a1942',
          bottomLeft: '#f39c12',
          bottomRight: '#e74c3c',
        },
        anchors: [0, 3, 8, 11],
        tileShape: 'square',
      },
      {
        id: 'tutorial-3',
        name: 'Океан',
        cols: 4,
        rows: 4,
        colors: {
          topLeft: '#0c2461',
          topRight: '#1e3799',
          bottomLeft: '#0a3d62',
          bottomRight: '#82ccdd',
        },
        anchors: [0, 3, 12, 15],
        tileShape: 'square',
      },
    ],
  },
  {
    id: 'forest',
    name: 'Лесные тона',
    description: 'Оттенки зеленого и коричневого',
    levels: [
      {
        id: 'forest-1',
        name: 'Листва',
        cols: 4,
        rows: 4,
        colors: {
          topLeft: '#1e8449',
          topRight: '#58d68d',
          bottomLeft: '#145a32',
          bottomRight: '#82e0aa',
        },
        anchors: [0, 3, 12, 15],
        tileShape: 'square',
      },
      {
        id: 'forest-2',
        name: 'Мох',
        cols: 5,
        rows: 4,
        colors: {
          topLeft: '#0b5345',
          topRight: '#1e8449',
          bottomLeft: '#104728',
          bottomRight: '#abebc6',
        },
        anchors: [0, 4, 15, 19],
        tileShape: 'square',
      },
      {
        id: 'forest-3',
        name: 'Папоротник',
        cols: 5,
        rows: 5,
        colors: {
          topLeft: '#0b3d0b',
          topRight: '#27ae60',
          bottomLeft: '#1d8348',
          bottomRight: '#d5f5e3',
        },
        anchors: [0, 4, 12, 20, 24],
        tileShape: 'square',
      },
      {
        id: 'forest-4',
        name: 'Древний лес',
        cols: 6,
        rows: 5,
        colors: {
          topLeft: '#0a2f0a',
          topRight: '#196f3d',
          bottomLeft: '#145a32',
          bottomRight: '#7dcea0',
        },
        anchors: [0, 5, 14, 15, 24, 29],
        tileShape: 'square',
      },
    ],
  },
  {
    id: 'sunset',
    name: 'Закат',
    description: 'Теплые оттенки заката',
    levels: [
      {
        id: 'sunset-1',
        name: 'Сумерки',
        cols: 4,
        rows: 4,
        colors: {
          topLeft: '#1a1a2e',
          topRight: '#4a235a',
          bottomLeft: '#f39c12',
          bottomRight: '#e74c3c',
        },
        anchors: [0, 3, 12, 15],
        tileShape: 'square',
      },
      {
        id: 'sunset-2',
        name: 'Горизонт',
        cols: 5,
        rows: 4,
        colors: {
          topLeft: '#2c3e50',
          topRight: '#8e44ad',
          bottomLeft: '#f1c40f',
          bottomRight: '#e67e22',
        },
        anchors: [0, 4, 15, 19],
        tileShape: 'square',
      },
      {
        id: 'sunset-3',
        name: 'Пламя',
        cols: 5,
        rows: 5,
        colors: {
          topLeft: '#7b241c',
          topRight: '#c0392b',
          bottomLeft: '#f39c12',
          bottomRight: '#f7dc6f',
        },
        anchors: [0, 4, 12, 20, 24],
        tileShape: 'square',
      },
      {
        id: 'sunset-4',
        name: 'Магма',
        cols: 6,
        rows: 5,
        colors: {
          topLeft: '#1a0a0a',
          topRight: '#641e16',
          bottomLeft: '#c0392b',
          bottomRight: '#f5b041',
        },
        anchors: [0, 5, 14, 15, 24, 29],
        tileShape: 'circle',
      },
    ],
  },
  {
    id: 'ocean',
    name: 'Океан',
    description: 'Голубые и бирюзовые оттенки',
    levels: [
      {
        id: 'ocean-1',
        name: 'Лагуна',
        cols: 4,
        rows: 4,
        colors: {
          topLeft: '#1b4f72',
          topRight: '#2e86ab',
          bottomLeft: '#117a65',
          bottomRight: '#76d7c4',
        },
        anchors: [0, 3, 12, 15],
        tileShape: 'square',
      },
      {
        id: 'ocean-2',
        name: 'Глубина',
        cols: 5,
        rows: 4,
        colors: {
          topLeft: '#0a1628',
          topRight: '#1a5276',
          bottomLeft: '#154360',
          bottomRight: '#85c1e9',
        },
        anchors: [0, 4, 15, 19],
        tileShape: 'square',
      },
      {
        id: 'ocean-3',
        name: 'Коралл',
        cols: 5,
        rows: 5,
        colors: {
          topLeft: '#0e6655',
          topRight: '#148f77',
          bottomLeft: '#1abc9c',
          bottomRight: '#a3e4d7',
        },
        anchors: [0, 4, 12, 20, 24],
        tileShape: 'circle',
      },
      {
        id: 'ocean-4',
        name: 'Атлантида',
        cols: 6,
        rows: 6,
        colors: {
          topLeft: '#0a192f',
          topRight: '#172a45',
          bottomLeft: '#2980b9',
          bottomRight: '#a9cce3',
        },
        anchors: [0, 5, 17, 18, 30, 35],
        tileShape: 'square',
      },
    ],
  },
  {
    id: 'lavender',
    name: 'Лаванда',
    description: 'Фиолетовые и розовые оттенки',
    levels: [
      {
        id: 'lavender-1',
        name: 'Утро',
        cols: 4,
        rows: 4,
        colors: {
          topLeft: '#4a235a',
          topRight: '#7d3c98',
          bottomLeft: '#a569bd',
          bottomRight: '#e8daef',
        },
        anchors: [0, 3, 12, 15],
        tileShape: 'square',
      },
      {
        id: 'lavender-2',
        name: 'Поле',
        cols: 5,
        rows: 4,
        colors: {
          topLeft: '#2e1a47',
          topRight: '#6c3483',
          bottomLeft: '#8e44ad',
          bottomRight: '#d7bde2',
        },
        anchors: [0, 4, 15, 19],
        tileShape: 'square',
      },
      {
        id: 'lavender-3',
        name: 'Аметист',
        cols: 5,
        rows: 5,
        colors: {
          topLeft: '#1a0a2e',
          topRight: '#512e5f',
          bottomLeft: '#76448a',
          bottomRight: '#f5eef8',
        },
        anchors: [0, 4, 12, 20, 24],
        tileShape: 'hexagon',
      },
      {
        id: 'lavender-4',
        name: 'Космос',
        cols: 6,
        rows: 6,
        colors: {
          topLeft: '#0a0a1a',
          topRight: '#2c0a37',
          bottomLeft: '#4a235a',
          bottomRight: '#bb8fce',
        },
        anchors: [0, 5, 17, 18, 30, 35],
        tileShape: 'circle',
      },
    ],
  },
  {
    id: 'advanced',
    name: 'Продвинутые',
    description: 'Сложные уровни для экспертов',
    levels: [
      {
        id: 'advanced-1',
        name: 'Радуга',
        cols: 6,
        rows: 5,
        colors: {
          topLeft: '#e74c3c',
          topRight: '#9b59b6',
          bottomLeft: '#f1c40f',
          bottomRight: '#3498db',
        },
        anchors: [0, 5, 24, 29],
        tileShape: 'square',
      },
      {
        id: 'advanced-2',
        name: 'Северное сияние',
        cols: 6,
        rows: 6,
        colors: {
          topLeft: '#0a3d0a',
          topRight: '#1abc9c',
          bottomLeft: '#2c3e50',
          bottomRight: '#9b59b6',
        },
        anchors: [0, 5, 17, 18, 30, 35],
        tileShape: 'square',
      },
      {
        id: 'advanced-3',
        name: 'Галактика',
        cols: 7,
        rows: 6,
        colors: {
          topLeft: '#0a0a14',
          topRight: '#1a1a3e',
          bottomLeft: '#4a235a',
          bottomRight: '#f39c12',
        },
        anchors: [0, 6, 20, 21, 35, 41],
        tileShape: 'circle',
      },
      {
        id: 'advanced-4',
        name: 'Мастер',
        cols: 7,
        rows: 7,
        colors: {
          topLeft: '#1a2a3a',
          topRight: '#3a5a7a',
          bottomLeft: '#5a3a1a',
          bottomRight: '#9a7a5a',
        },
        anchors: [0, 6, 24, 42, 48],
        tileShape: 'square',
      },
    ],
  },
  {
    id: 'mega',
    name: 'Мега',
    description: 'Огромные сетки для настоящих профи',
    levels: [
      {
        id: 'mega-1',
        name: 'Широкий горизонт',
        cols: 8,
        rows: 6,
        colors: {
          topLeft: '#2c3e50',
          topRight: '#e74c3c',
          bottomLeft: '#3498db',
          bottomRight: '#f39c12',
        },
        anchors: [0, 7, 40, 47],
        tileShape: 'square',
      },
      {
        id: 'mega-2',
        name: 'Квадрат 8x8',
        cols: 8,
        rows: 8,
        colors: {
          topLeft: '#1a1a2e',
          topRight: '#16a085',
          bottomLeft: '#8e44ad',
          bottomRight: '#f1c40f',
        },
        anchors: [0, 7, 56, 63],
        tileShape: 'square',
      },
      {
        id: 'mega-3',
        name: 'Осенний лес',
        cols: 9,
        rows: 7,
        colors: {
          topLeft: '#784212',
          topRight: '#d35400',
          bottomLeft: '#1e8449',
          bottomRight: '#f7dc6f',
        },
        anchors: [0, 8, 54, 62],
        tileShape: 'square',
      },
      {
        id: 'mega-4',
        name: 'Ночное небо',
        cols: 8,
        rows: 8,
        colors: {
          topLeft: '#0a0a14',
          topRight: '#1a1a3e',
          bottomLeft: '#2c3e50',
          bottomRight: '#5dade2',
        },
        anchors: [0, 7, 27, 36, 56, 63],
        tileShape: 'circle',
      },
      {
        id: 'mega-5',
        name: 'Весенний луг',
        cols: 8,
        rows: 7,
        colors: {
          topLeft: '#27ae60',
          topRight: '#f1c40f',
          bottomLeft: '#16a085',
          bottomRight: '#e8f8f5',
        },
        anchors: [0, 7, 48, 55],
        tileShape: 'square',
      },
      {
        id: 'mega-6',
        name: 'Виноградник',
        cols: 9,
        rows: 6,
        colors: {
          topLeft: '#4a235a',
          topRight: '#7d3c98',
          bottomLeft: '#1e8449',
          bottomRight: '#abebc6',
        },
        anchors: [0, 8, 45, 53],
        tileShape: 'square',
      },
      {
        id: 'mega-7',
        name: 'Рассветное море',
        cols: 9,
        rows: 8,
        colors: {
          topLeft: '#ff6b6b',
          topRight: '#feca57',
          bottomLeft: '#1a535c',
          bottomRight: '#4ecdc4',
        },
        anchors: [0, 8, 63, 71],
        tileShape: 'square',
      },
      {
        id: 'mega-8',
        name: 'Туманный лес',
        cols: 8,
        rows: 9,
        colors: {
          topLeft: '#2d3436',
          topRight: '#636e72',
          bottomLeft: '#00b894',
          bottomRight: '#55efc4',
        },
        anchors: [0, 7, 32, 39, 64, 71],
        tileShape: 'square',
      },
      {
        id: 'mega-9',
        name: 'Медовые соты',
        cols: 9,
        rows: 9,
        colors: {
          topLeft: '#f39c12',
          topRight: '#e74c3c',
          bottomLeft: '#f7dc6f',
          bottomRight: '#fdebd0',
        },
        anchors: [0, 8, 72, 80],
        tileShape: 'hexagon',
      },
      {
        id: 'mega-10',
        name: 'Северное утро',
        cols: 9,
        rows: 8,
        colors: {
          topLeft: '#dfe6e9',
          topRight: '#74b9ff',
          bottomLeft: '#a29bfe',
          bottomRight: '#fd79a8',
        },
        anchors: [0, 8, 31, 40, 63, 71],
        tileShape: 'square',
      },
      {
        id: 'mega-11',
        name: 'Джунгли',
        cols: 8,
        rows: 9,
        colors: {
          topLeft: '#0a3d0a',
          topRight: '#27ae60',
          bottomLeft: '#1e3d1e',
          bottomRight: '#82e0aa',
        },
        anchors: [0, 7, 64, 71],
        tileShape: 'square',
      },
      {
        id: 'mega-12',
        name: 'Коралловый риф',
        cols: 9,
        rows: 9,
        colors: {
          topLeft: '#0097a7',
          topRight: '#00bcd4',
          bottomLeft: '#ff7043',
          bottomRight: '#ffab91',
        },
        anchors: [0, 8, 36, 44, 72, 80],
        tileShape: 'circle',
      },
    ],
  },
  {
    id: 'extreme',
    name: 'Экстремальные',
    description: 'Уровни 10x10 и больше',
    levels: [
      {
        id: 'extreme-1',
        name: 'Сотня',
        cols: 10,
        rows: 10,
        colors: {
          topLeft: '#c0392b',
          topRight: '#8e44ad',
          bottomLeft: '#f39c12',
          bottomRight: '#27ae60',
        },
        anchors: [0, 9, 90, 99],
        tileShape: 'square',
      },
      {
        id: 'extreme-2',
        name: 'Морская гладь',
        cols: 10,
        rows: 10,
        colors: {
          topLeft: '#0a192f',
          topRight: '#1a365d',
          bottomLeft: '#2c5aa0',
          bottomRight: '#87ceeb',
        },
        anchors: [0, 9, 45, 54, 90, 99],
        tileShape: 'square',
      },
      {
        id: 'extreme-3',
        name: 'Пустыня',
        cols: 12,
        rows: 8,
        colors: {
          topLeft: '#f4d03f',
          topRight: '#dc7633',
          bottomLeft: '#fdebd0',
          bottomRight: '#a04000',
        },
        anchors: [0, 11, 84, 95],
        tileShape: 'square',
      },
      {
        id: 'extreme-4',
        name: 'Ледник',
        cols: 10,
        rows: 12,
        colors: {
          topLeft: '#d6eaf8',
          topRight: '#aed6f1',
          bottomLeft: '#5dade2',
          bottomRight: '#2e86ab',
        },
        anchors: [0, 9, 55, 64, 110, 119],
        tileShape: 'square',
      },
      {
        id: 'extreme-5',
        name: 'Вулкан',
        cols: 10,
        rows: 10,
        colors: {
          topLeft: '#1a0a0a',
          topRight: '#4a0a0a',
          bottomLeft: '#e74c3c',
          bottomRight: '#f39c12',
        },
        anchors: [0, 9, 90, 99],
        tileShape: 'square',
      },
      {
        id: 'extreme-6',
        name: 'Аврора',
        cols: 11,
        rows: 9,
        colors: {
          topLeft: '#0a0a2e',
          topRight: '#1abc9c',
          bottomLeft: '#9b59b6',
          bottomRight: '#3498db',
        },
        anchors: [0, 10, 88, 98],
        tileShape: 'square',
      },
      {
        id: 'extreme-7',
        name: 'Саванна',
        cols: 12,
        rows: 9,
        colors: {
          topLeft: '#f39c12',
          topRight: '#d35400',
          bottomLeft: '#27ae60',
          bottomRight: '#f7dc6f',
        },
        anchors: [0, 11, 96, 107],
        tileShape: 'square',
      },
      {
        id: 'extreme-8',
        name: 'Ночной город',
        cols: 10,
        rows: 11,
        colors: {
          topLeft: '#0a0a14',
          topRight: '#1a1a3e',
          bottomLeft: '#f39c12',
          bottomRight: '#e74c3c',
        },
        anchors: [0, 9, 50, 59, 100, 109],
        tileShape: 'square',
      },
      {
        id: 'extreme-9',
        name: 'Тропический остров',
        cols: 11,
        rows: 10,
        colors: {
          topLeft: '#00cec9',
          topRight: '#0984e3',
          bottomLeft: '#fdcb6e',
          bottomRight: '#00b894',
        },
        anchors: [0, 10, 99, 109],
        tileShape: 'square',
      },
      {
        id: 'extreme-10',
        name: 'Лавовое поле',
        cols: 12,
        rows: 10,
        colors: {
          topLeft: '#2d3436',
          topRight: '#636e72',
          bottomLeft: '#d63031',
          bottomRight: '#fdcb6e',
        },
        anchors: [0, 11, 54, 65, 108, 119],
        tileShape: 'circle',
      },
      {
        id: 'extreme-11',
        name: 'Весенний сад',
        cols: 10,
        rows: 12,
        colors: {
          topLeft: '#fd79a8',
          topRight: '#e84393',
          bottomLeft: '#00b894',
          bottomRight: '#55efc4',
        },
        anchors: [0, 9, 110, 119],
        tileShape: 'square',
      },
      {
        id: 'extreme-12',
        name: 'Штормовое море',
        cols: 11,
        rows: 11,
        colors: {
          topLeft: '#2d3436',
          topRight: '#636e72',
          bottomLeft: '#0984e3',
          bottomRight: '#74b9ff',
        },
        anchors: [0, 10, 55, 65, 110, 120],
        tileShape: 'square',
      },
      {
        id: 'extreme-13',
        name: 'Пряности',
        cols: 12,
        rows: 10,
        colors: {
          topLeft: '#6c3483',
          topRight: '#c0392b',
          bottomLeft: '#f39c12',
          bottomRight: '#27ae60',
        },
        anchors: [0, 11, 108, 119],
        tileShape: 'hexagon',
      },
      {
        id: 'extreme-14',
        name: 'Зимний вечер',
        cols: 10,
        rows: 12,
        colors: {
          topLeft: '#2c3e50',
          topRight: '#5d6d7e',
          bottomLeft: '#aed6f1',
          bottomRight: '#ebf5fb',
        },
        anchors: [0, 9, 55, 64, 110, 119],
        tileShape: 'square',
      },
      {
        id: 'extreme-15',
        name: 'Неоновый город',
        cols: 12,
        rows: 10,
        colors: {
          topLeft: '#0a0a14',
          topRight: '#e84393',
          bottomLeft: '#00cec9',
          bottomRight: '#fdcb6e',
        },
        anchors: [0, 11, 108, 119],
        tileShape: 'square',
      },
    ],
  },
  {
    id: 'master',
    name: 'Мастерские',
    description: 'Для тех, кто готов ко всему',
    levels: [
      {
        id: 'master-1',
        name: 'Полотно 10x15',
        cols: 10,
        rows: 15,
        colors: {
          topLeft: '#1a1a2e',
          topRight: '#e74c3c',
          bottomLeft: '#3498db',
          bottomRight: '#2ecc71',
        },
        anchors: [0, 9, 140, 149],
        tileShape: 'square',
      },
      {
        id: 'master-2',
        name: 'Широкое полотно',
        cols: 15,
        rows: 10,
        colors: {
          topLeft: '#4a235a',
          topRight: '#f1c40f',
          bottomLeft: '#1abc9c',
          bottomRight: '#e74c3c',
        },
        anchors: [0, 14, 135, 149],
        tileShape: 'square',
      },
      {
        id: 'master-3',
        name: 'Мозаика 12x12',
        cols: 12,
        rows: 12,
        colors: {
          topLeft: '#2c3e50',
          topRight: '#9b59b6',
          bottomLeft: '#e67e22',
          bottomRight: '#1abc9c',
        },
        anchors: [0, 11, 66, 77, 132, 143],
        tileShape: 'square',
      },
      {
        id: 'master-4',
        name: 'Гигант 15x10',
        cols: 15,
        rows: 10,
        colors: {
          topLeft: '#0a0a1a',
          topRight: '#c0392b',
          bottomLeft: '#27ae60',
          bottomRight: '#f39c12',
        },
        anchors: [0, 14, 67, 82, 135, 149],
        tileShape: 'circle',
      },
      {
        id: 'master-5',
        name: 'Рассвет над морем',
        cols: 12,
        rows: 10,
        colors: {
          topLeft: '#ff7675',
          topRight: '#fdcb6e',
          bottomLeft: '#0984e3',
          bottomRight: '#74b9ff',
        },
        anchors: [0, 11, 108, 119],
        tileShape: 'square',
      },
      {
        id: 'master-6',
        name: 'Горный хребет',
        cols: 10,
        rows: 13,
        colors: {
          topLeft: '#dfe6e9',
          topRight: '#b2bec3',
          bottomLeft: '#2d3436',
          bottomRight: '#636e72',
        },
        anchors: [0, 9, 60, 69, 120, 129],
        tileShape: 'square',
      },
      {
        id: 'master-7',
        name: 'Тропический лес',
        cols: 13,
        rows: 10,
        colors: {
          topLeft: '#00b894',
          topRight: '#55efc4',
          bottomLeft: '#006266',
          bottomRight: '#1dd1a1',
        },
        anchors: [0, 12, 117, 129],
        tileShape: 'square',
      },
      {
        id: 'master-8',
        name: 'Вечерний Токио',
        cols: 10,
        rows: 14,
        colors: {
          topLeft: '#0a0a14',
          topRight: '#e84393',
          bottomLeft: '#00cec9',
          bottomRight: '#a29bfe',
        },
        anchors: [0, 9, 65, 74, 130, 139],
        tileShape: 'square',
      },
      {
        id: 'master-9',
        name: 'Осенний парк',
        cols: 14,
        rows: 10,
        colors: {
          topLeft: '#d35400',
          topRight: '#e74c3c',
          bottomLeft: '#f39c12',
          bottomRight: '#f7dc6f',
        },
        anchors: [0, 13, 126, 139],
        tileShape: 'square',
      },
      {
        id: 'master-10',
        name: 'Подводный мир',
        cols: 12,
        rows: 12,
        colors: {
          topLeft: '#0a192f',
          topRight: '#1a365d',
          bottomLeft: '#00cec9',
          bottomRight: '#81ecec',
        },
        anchors: [0, 11, 132, 143],
        tileShape: 'circle',
      },
      {
        id: 'master-11',
        name: 'Песчаные дюны',
        cols: 15,
        rows: 10,
        colors: {
          topLeft: '#f9ca24',
          topRight: '#f0932b',
          bottomLeft: '#ffeaa7',
          bottomRight: '#fdcb6e',
        },
        anchors: [0, 14, 67, 82, 135, 149],
        tileShape: 'square',
      },
      {
        id: 'master-12',
        name: 'Северное сияние',
        cols: 10,
        rows: 15,
        colors: {
          topLeft: '#0a0a2e',
          topRight: '#1abc9c',
          bottomLeft: '#6c5ce7',
          bottomRight: '#a29bfe',
        },
        anchors: [0, 9, 70, 79, 140, 149],
        tileShape: 'square',
      },
      {
        id: 'master-13',
        name: 'Магический кристалл',
        cols: 13,
        rows: 11,
        colors: {
          topLeft: '#6c3483',
          topRight: '#a569bd',
          bottomLeft: '#1abc9c',
          bottomRight: '#76d7c4',
        },
        anchors: [0, 12, 130, 142],
        tileShape: 'hexagon',
      },
      {
        id: 'master-14',
        name: 'Цветущая сакура',
        cols: 11,
        rows: 13,
        colors: {
          topLeft: '#fd79a8',
          topRight: '#fab1a0',
          bottomLeft: '#00b894',
          bottomRight: '#55efc4',
        },
        anchors: [0, 10, 66, 76, 132, 142],
        tileShape: 'square',
      },
      {
        id: 'master-15',
        name: 'Звездная ночь',
        cols: 12,
        rows: 12,
        colors: {
          topLeft: '#0a0a1a',
          topRight: '#2d3436',
          bottomLeft: '#6c5ce7',
          bottomRight: '#fdcb6e',
        },
        anchors: [0, 11, 66, 77, 132, 143],
        tileShape: 'circle',
      },
    ],
  },
  {
    id: 'ultimate',
    name: 'Ультимативные',
    description: 'Самые большие и сложные уровни',
    levels: [
      {
        id: 'ultimate-1',
        name: 'Бескрайнее поле',
        cols: 12,
        rows: 15,
        colors: {
          topLeft: '#145a32',
          topRight: '#58d68d',
          bottomLeft: '#0b5345',
          bottomRight: '#abebc6',
        },
        anchors: [0, 11, 168, 179],
        tileShape: 'square',
      },
      {
        id: 'ultimate-2',
        name: 'Огненный закат',
        cols: 15,
        rows: 12,
        colors: {
          topLeft: '#1a0a0a',
          topRight: '#641e16',
          bottomLeft: '#f39c12',
          bottomRight: '#f7dc6f',
        },
        anchors: [0, 14, 82, 97, 165, 179],
        tileShape: 'square',
      },
      {
        id: 'ultimate-3',
        name: 'Космическая бездна',
        cols: 14,
        rows: 14,
        colors: {
          topLeft: '#0a0a14',
          topRight: '#2c0a37',
          bottomLeft: '#1a365d',
          bottomRight: '#9b59b6',
        },
        anchors: [0, 13, 91, 104, 182, 195],
        tileShape: 'circle',
      },
      {
        id: 'ultimate-4',
        name: 'Абсолют 15x15',
        cols: 15,
        rows: 15,
        colors: {
          topLeft: '#1a2a3a',
          topRight: '#e74c3c',
          bottomLeft: '#2ecc71',
          bottomRight: '#9b59b6',
        },
        anchors: [0, 14, 210, 224],
        tileShape: 'square',
      },
      {
        id: 'ultimate-5',
        name: 'Океанская глубина',
        cols: 13,
        rows: 13,
        colors: {
          topLeft: '#0a192f',
          topRight: '#1a365d',
          bottomLeft: '#0984e3',
          bottomRight: '#74b9ff',
        },
        anchors: [0, 12, 156, 168],
        tileShape: 'square',
      },
      {
        id: 'ultimate-6',
        name: 'Закат в пустыне',
        cols: 14,
        rows: 12,
        colors: {
          topLeft: '#d35400',
          topRight: '#e74c3c',
          bottomLeft: '#f9ca24',
          bottomRight: '#ffeaa7',
        },
        anchors: [0, 13, 154, 167],
        tileShape: 'square',
      },
      {
        id: 'ultimate-7',
        name: 'Ледяной замок',
        cols: 12,
        rows: 14,
        colors: {
          topLeft: '#dfe6e9',
          topRight: '#b2bec3',
          bottomLeft: '#74b9ff',
          bottomRight: '#0984e3',
        },
        anchors: [0, 11, 78, 89, 156, 167],
        tileShape: 'square',
      },
      {
        id: 'ultimate-8',
        name: 'Вечный лес',
        cols: 13,
        rows: 14,
        colors: {
          topLeft: '#006266',
          topRight: '#009432',
          bottomLeft: '#1e3d1e',
          bottomRight: '#a3cb38',
        },
        anchors: [0, 12, 169, 181],
        tileShape: 'square',
      },
      {
        id: 'ultimate-9',
        name: 'Галактический вихрь',
        cols: 14,
        rows: 13,
        colors: {
          topLeft: '#0a0a1a',
          topRight: '#6c5ce7',
          bottomLeft: '#e84393',
          bottomRight: '#fdcb6e',
        },
        anchors: [0, 13, 84, 97, 168, 181],
        tileShape: 'circle',
      },
      {
        id: 'ultimate-10',
        name: 'Пламенный танец',
        cols: 15,
        rows: 13,
        colors: {
          topLeft: '#b71540',
          topRight: '#e84118',
          bottomLeft: '#f9ca24',
          bottomRight: '#ffeaa7',
        },
        anchors: [0, 14, 180, 194],
        tileShape: 'square',
      },
      {
        id: 'ultimate-11',
        name: 'Морозное утро',
        cols: 13,
        rows: 15,
        colors: {
          topLeft: '#dfe6e9',
          topRight: '#b2bec3',
          bottomLeft: '#a29bfe',
          bottomRight: '#6c5ce7',
        },
        anchors: [0, 12, 91, 103, 182, 194],
        tileShape: 'square',
      },
      {
        id: 'ultimate-12',
        name: 'Королевство теней',
        cols: 14,
        rows: 14,
        colors: {
          topLeft: '#0a0a14',
          topRight: '#2d3436',
          bottomLeft: '#636e72',
          bottomRight: '#b2bec3',
        },
        anchors: [0, 13, 91, 104, 182, 195],
        tileShape: 'square',
      },
      {
        id: 'ultimate-13',
        name: 'Радужный мост',
        cols: 15,
        rows: 14,
        colors: {
          topLeft: '#e74c3c',
          topRight: '#9b59b6',
          bottomLeft: '#f1c40f',
          bottomRight: '#1abc9c',
        },
        anchors: [0, 14, 195, 209],
        tileShape: 'hexagon',
      },
      {
        id: 'ultimate-14',
        name: 'Врата времени',
        cols: 14,
        rows: 15,
        colors: {
          topLeft: '#6c5ce7',
          topRight: '#a29bfe',
          bottomLeft: '#00cec9',
          bottomRight: '#81ecec',
        },
        anchors: [0, 13, 98, 111, 196, 209],
        tileShape: 'circle',
      },
      {
        id: 'ultimate-15',
        name: 'Бесконечность',
        cols: 15,
        rows: 15,
        colors: {
          topLeft: '#0a0a14',
          topRight: '#e84393',
          bottomLeft: '#00cec9',
          bottomRight: '#fdcb6e',
        },
        anchors: [0, 14, 105, 119, 210, 224],
        tileShape: 'square',
      },
    ],
  },
];

// Flatten all levels for easy access
export const ALL_LEVELS: LevelConfig[] = LEVEL_PACKS.flatMap(pack => pack.levels);

// Get level by ID
export const getLevelById = (id: string): LevelConfig | undefined => {
  return ALL_LEVELS.find(level => level.id === id);
};

// Get pack by level ID
export const getPackByLevelId = (levelId: string): LevelPack | undefined => {
  return LEVEL_PACKS.find(pack => pack.levels.some(level => level.id === levelId));
};

// Get next level
export const getNextLevel = (currentLevelId: string): LevelConfig | undefined => {
  const currentIndex = ALL_LEVELS.findIndex(level => level.id === currentLevelId);
  if (currentIndex === -1 || currentIndex === ALL_LEVELS.length - 1) return undefined;
  return ALL_LEVELS[currentIndex + 1];
};
